### ISSUE TITLE
ImportError: No module named regex

### ISSUE THREAD

**Issue by daviddoji** [davidmogar/normalizr#26]
I installed the library via pip but when I try to use it within a script I'm getting the following error:

ImportError: No module named regex

Following the traceback, apparently the error occurs when importing normalizr.regex as regex

**Comment by davidmogar** [comment]
Hi daviddoji,

What version of Python are you using?

**Comment by daviddoji** [comment]
Python 2.7 with Canopy IDE

**Comment by davidmogar** [comment]
Yeah, seems like something to fix. In the mean time you have two options:

- Clone the repository and use the setup.py as described in the [README.md](https://github.com/davidmogar/normalizr/blob/master/README.md) file.
- Use Python 3.

Hope this can help you ;)

**Comment by davidmogar** [comment]
Just to shed some light, the behavior is the expected for the pip package. Initially, normalizr only supported Python 3. This has changed nowadays as you can see in the [README.md](https://github.com/davidmogar/normalizr/blob/master/README.md) file. The problem here is that the package hasn't been updated in Pypi. Will fix as said in #27.
